# This is a basic workflow to help you get started with Actions
name: run-tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the toml-test suite.
  build-toml-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'latest'
      - name: Check-out https://github.com/BurntSushi/toml-test
        run: git clone https://github.com/BurntSushi/toml-test
      - name: Build toml-test
        working-directory: toml-test
        run: go build ./cmd/toml-test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: toml-test
          path: toml-test/toml-test
