# This is a basic workflow to help you get started with Actions
name: run-tests

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build the toml-test suite.
  build-toml-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Check-out https://github.com/BurntSushi/toml-test
        run: git clone https://github.com/BurntSushi/toml-test.git
      - name: Build toml-test
        working-directory: toml-test
        run: go build ./cmd/toml-test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: toml-test
          path: toml-test/toml-test
          retention-days: 5

  test-burntsushi-toml:
    runs-on: ubuntu-latest
    needs: build-toml-test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - uses: actions/download-artifact@v3
        with:
          name: toml-test
      - name: Prepare toml-test executable
        run: chmod a+x ./toml-test
      - name: Check-out https://github.com/BurntSushi/toml
        run: git clone https://github.com/BurntSushi/toml.git burntsushi-toml
      - name: Build TOML decoder
        working-directory: burntsushi-toml
        run: go build ./cmd/toml-test-decoder
      - name: Test TOML decoder
        run: ./toml-test -toml 1.0.0 burntsushi-toml/toml-test-decoder

  test-python311-tomllib:
    runs-on: ubuntu-latest
    needs: build-toml-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@v3
        with:
          name: toml-test
      - name: Prepare toml-test executable
        run: chmod a+x ./toml-test
      - name: Display working directory contents
        run: ls -lR
      - name: Test TOML decoder
        run: ./toml-test -toml 1.0.0 python/tomllib-decoder.py

